config/routes.rb
Rails.application.routes.draw do
  get 'energy/index'
  get 'energy/show'
  get 'energy/new'
  post 'energy/import'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'energy#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day_production.rb
class DayProduction < ApplicationRecord
    has_many :hourly_productions, foreign_key: 'day', class_name: 'HourlyProduction'
end

app/models/hourly_production.rb
class HourlyProduction < ApplicationRecord
    belongs_to :onduleur

    require 'csv'
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            HourlyProduction.create!(
                identifier: row[0],
                date_time: row[1],
                energy: row[2],
                day: Date.parse(row[1].to_s)
            )
        end
    end

end

app/models/onduleur.rb
class Onduleur < ApplicationRecord
    has_many :hourly_productions, class_name: "hourly_production", foreign_key: "indentifier"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/energy_controller.rb
class EnergyController < ApplicationController
  def index
    @day_productions= DayProduction.all
  end

  def def new
  end
  

  def import  
    HourlyProduction.import(params[:file])

    @days = HourlyProduction.select(:day).distinct
    @days.each do |day|
      total = 0
      @hourly_prods = HourlyProduction.where(day: day.day)
      @hourly_prods.each do |h_p|
        total += h_p.energy
      end
      DayProduction.create!(day: day.day, energy_total: total)
    end

    redirect_to energy_index_path, notice: "Data succesfully imported" 
  end

  def show
    @hourly_prods = HourlyProduction.where(day: params["format"])
    @day_production = DayProduction.find_by(day: params["format"]).energy_total
    #raise
    #@energy_total = DayProduction.select
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/energy_helper.rb
module EnergyHelper
end

app/views/energy/index.html.erb
<h1>Bienvenue sur la page de visualisation</h1>

<div>
<div>
<h2>Production totale par jour </h2>
    <table>
        <thead>
            <tr>Day</tr>
            <tr>Energy totale </tr>
        </thead>
        <tbody>
            <% @day_productions.each do |d_p| %>
            <tr >
                <td> <%= d_p.day %></td>
                <td> <%= d_p.energy_total %></td>
                <td><%=link_to "Voir les détails", energy_show_path(d_p.day) %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>


<div>

    <h2><%= link_to "Importer des données csv", energy_new_path  %></h2>
</div>

app/views/energy/new.html.erb
<%= form_tag energy_import_path, multipart: true, method: :post do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import csv" %>
<% end %>

app/views/energy/show.html.erb
<h1>Somme des energy</h1>

<table>
<thead>
    <tr>identifier</tr>
    <tr>hours</tr>
    <tr>Energy</tr>
</thead>
<tbody>
    <% @hourly_prods.each do |h_p| %>
    <tr>
        <td><%= h_p.identifier %></td>
        <td><%= h_p.date_time %></td>
        <td><%= h_p.energy %></td>
    </tr>
    <% end %>
    <tr>
        <td>Energy total journaliere</td>
        <td><%= @day_production %></td>
    </tr>
</tbody>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EpicesTestBackCisse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>